events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [

    # /polls/
    path('', views.index, name='index'),

    # Event URL Patterns
    path('view/<int:id>/', views.view_event, name='view_event'),
    path('edit/<int:id>/', views.edit_event, name='edit_event'),
    path('create/', views.create_event, name='create_event'),

    # AJAX URL Patterns
    path('add/', views.add_event, name='add_event'),
    path('add_entree/', views.add_entree, name='add_entree'),
    path('remove_entree/', views.remove_entree, name='remove_entree'),

]

hoops/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(route='', view=include('main.urls')),
    path(route='stats/', view=include('stats.urls')),
    path(route='polls/', view=include('polls.urls')),
    path(route='events/', view=include('events.urls')),
    path(route='wrestling/', view=include('wrestling.urls')),
    path(route='admin/', view=admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # Discord URL patterns
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("login/discord/", views.login_discord, name="login_discord"),
    path("login/discord/redirect/", views.login_discord_redirect, name="login_discord_redirect"),
    path("logout/", views.logout, name="logout"),

    # Player URL patterns
    path("player/<int:id>/", views.player, name="player"),
    path("player/upgrade/<int:id>/", views.upgrade_player, name="upgrade_player"),
    path("player/create/", views.create_player, name="create_player"),
    path("players/", views.free_agents, name="players"),
    path("logs/upgrades/<int:id>/", views.upgrade_logs, name="upgrade_logs"),
    path("logs/cash/<int:id>/", views.cash_logs, name="cash_logs"),
    path("players/builder/", views.mock_builder, name="mock_builder"),
    path("players/vitals/update/<int:id>/", views.update_player_vitals, name="update_player_vitals"),
    path("players/pending/update/", views.update_player_pending_upgrades, name="update_player_pending_upgrades"),
    path("player/physicals/edit/<int:id>/", views.edit_physicals, name="edit_physicals"),
    # path("players/free-agents/", views.free_agents, name="free_agents"),
    path("player/styles/<int:id>/", views.player_styles, name="player_styles"),
    path("player/cash/add/", views.add_player_cash, name="add_player_cash"),
    path("player/cash/take/", views.take_player_cash, name="take_player_cash"),
    path("player/daily/reward/collect/", views.daily_rewards, name="daily_rewards"),
    path("player/upgrade/scrape/<int:id>/", views.scrape_tendencies, name="scrape_tendencies"),
    path("player/integrate/", views.integrate_player, name="integrate_player"),

    # Team URL patterns
    path("team/<int:id>/", views.team, name="team"),
    path("teams/", views.teams, name="teams"),
    path("team/trade/", views.trade, name="trade"),
    path("team/trade/accept/<int:id>/", views.accept_trade, name="accept_trade"),
    path("team/trade/decline/<int:id>/", views.decline_trade, name="decline_trade"),
    path("trades/panel/", views.trade_panel, name="trade_panel"),
    path("team/trade/finalize/", views.check_finalize_trade, name="check_finalize_trade"),

    # Miscellaneous URL patterns
    path("upgrades/pending/", views.upgrades_pending, name="upgrades_pending"),
    path("frivolities/", views.frivolities, name="frivolities"),
    path("coupons/", views.coupons, name="coupons"),
    path("ads.txt", views.ad_view.as_view()),

    # Htmx URL patterns
    path("players/search/", views.check_player_search, name="check_player_search"),
    path("teams/search/", views.check_team_search, name="check_team_search"),
    path("coupons/redeem/", views.check_coupon_code, name="check_coupon_code"),
    path("keys/redeem/", views.check_license_key, name="check_license_key"),
    path("players/attributes/", views.check_starting_attributes, name="check_starting_attributes"),
    path("positions/count/", views.check_position_count, name="check_position_count"),
    path("upgrades/validate/", views.check_upgrade_validation, name="check_upgrade_validation"),
    path("players/leaders/", views.check_player_leaders, name="check_player_leaders"),
    path("metas/leaders/", views.check_meta_leaders, name="check_meta_leaders"),
    path("attributes/leaders/", views.check_attribute_leaders, name="check_attribute_leaders"),
    path("teams/roster/", views.check_team_roster, name="check_team_roster"),
    path("teams/trade/", views.check_trade_validation, name="check_trade_validation"),
    path("notifications/mark/read/", views.check_read_notification, name="check_read_notification"),
    path("player/daily/reward/", views.check_daily_reward, name="check_daily_reward"),
    path("player/weight/check/", views.check_weight_change, name="check_weight_change"),
    path("players/free-agents/search/", views.check_free_agent_search, name="check_free_agent_search"),
    path("contract/offer/", views.check_contract_offer, name="check_contract_offer"),
    path("contract/revoke/", views.check_contract_revoke, name="check_contract_revoke"),
    path("players/create/spent/", views.check_creation_spent, name="check_creation_spent"),
    path("players/integrate/", views.check_player_integration, name="check_player_integration"),

    # User URL patterns
    path("user/notifications/<int:id>/", views.notifications, name="notifications"),

    # API URL patterns
    path('players/cyberfaces/api/', views.cyberface_check, name='cyberface_check'),
    path('players/auto-collect/', views.auto_collect, name='auto_collect'),

]

events/models.py
# Django imports
from django.db import models

# Main application imports
from main.models import Player

# Create your models here.
class Event(models.Model):

    # Event fields
    title = models.CharField(max_length=100)
    description = models.TextField()
    rookies_allowed = models.BooleanField(default=False)
    free_agents_allowed = models.BooleanField(default=False)
    active_players_allowed = models.BooleanField(default=False)
    use_spent_limit = models.BooleanField(default=False)
    spent_limit = models.IntegerField(default=0)
    max_entrees = models.IntegerField(default=0)

    # Custom str method
    def __str__(self):
        return self.title

class Entree(models.Model):
    # Entree relationships
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    # Custom str method
    def __str__(self):
        return f"{self.player} - {self.event}"

events/forms.py
from django import forms

class EventForm(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    rookies_allowed = forms.BooleanField(required=False)
    free_agents_allowed = forms.BooleanField(required=False)
    active_players_allowed = forms.BooleanField(required=False)
    use_spent_limit = forms.BooleanField(required=False)
    spent_limit = forms.IntegerField(required=False)
    max_entrees = forms.IntegerField(required=False)

events/views.py
# Django imports
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import Sum
from django.template.loader import render_to_string
from django.utils import timezone
from django.views import View

# Main application imports
from main.models import Player

# Event application imports
from events.models import Event
from events.models import Entree
from events.forms import EventForm

# Event views
def index(request):
    # Create the context
    context = {
        "events": Event.objects.all(),
    }
    # Return the response
    return render(request, 'events/index.html', context)

def view_event(request, id):
    # Check if the event exists
    if not Event.objects.filter(id=id).exists():
        return HttpResponse("❌ That event does not exist.")
    # Create the context
    context = {
        "event": Event.objects.get(id=id),
        "entrees": Entree.objects.filter(event=id).order_by("-player__spent"),
        "entree_count": Entree.objects.filter(event=id).count(),
        "player_list": Player.objects.filter(discord_user=request.user),
    }
    # Return the response
    return render(request, 'events/viewing/view_event.html', context)

def create_event(request):
    # Check permissions
    if not request.user.can_edit_events:
        return HttpResponse("❌ You do not have permission to create events.")
    # Create the context
    context = {
        "create_event_form": EventForm,
    }
    # Return the response
    return render(request, 'events/editing/create_event.html', context)

def edit_event(request, id):
    return HttpResponse("Editing event")

# AJAX views
def add_event(request):
    if request.method == "POST":
        # Check permissions
        if not request.user.can_edit_events:
            return HttpResponse("❌ You do not have permission to add events.")
        # Create the event
        title = request.POST.get("title")
        description = request.POST.get("description")
        spent_limit = request.POST.get("spent_limit")
        max_entrees = request.POST.get("max_entrees")
        rookies_allowed = True if request.POST.get("rookies_allowed") else False
        free_agents_allowed = True if request.POST.get("free_agents_allowed") else False
        active_players_allowed = True if request.POST.get("active_players_allowed") else False
        use_spent_limit = True if request.POST.get("use_spent_limit") else False
        # Validate the event
        if not title or not description:
            return HttpResponse("❌ Please enter a title and description.")
        if use_spent_limit and not spent_limit:
            return HttpResponse("❌ Please enter a spent limit if you want to use one.")
        # Create & save the event
        event = Event(
            title=title,
            description=description,
            rookies_allowed=rookies_allowed,
            free_agents_allowed=free_agents_allowed,
            active_players_allowed=active_players_allowed,
            use_spent_limit=use_spent_limit,
            spent_limit=int(spent_limit),
            max_entrees=max_entrees,
        )
        event.save()
        # Return the success message (refresh page and clear form)
        messages.success(request, f"✅ Event added successfully! [#{event.id}]")
        response = HttpResponse()
        response['HX-Refresh'] = "true"
        return response

def add_entree(request):
    # Get some fields
    event_id = request.POST.get("event_id")
    id = request.POST.get("id")
    # Check for player & event
    if not Player.objects.filter(id=id).exists():
        return HttpResponse("❌ That player does not exist.")
    if not Event.objects.filter(id=event_id).exists():
        return HttpResponse("❌ That event does not exist.")
    # Get player & event
    player = Player.objects.get(id=id)
    event = Event.objects.get(id=event_id)
    # Check if user owns player
    if not player.discord_user == request.user:
        return HttpResponse("❌ You do not own that player.")
    # Check if player is already entered
    if Entree.objects.filter(player=player, event=event).exists():
        return HttpResponse("❌ You have already entered that event.")
    # Check if event is full
    if Entree.objects.filter(event=event).count() >= event.max_entrees:
        return HttpResponse("❌ That event is full.")
    # Find player eligibility statuses
    is_rookie = False
    is_free_agent = False
    is_active_player = False
    if player.years_played <= 1:
        is_rookie = True
    if player.current_team == None:
        is_free_agent = True
    if player.current_team and player.current_team.plays_in_main_league:
        is_active_player = True
    # Check if player is eligible
    if not event.rookies_allowed and is_rookie:
        return HttpResponse("❌ That event does not allow rookies.")
    if not event.free_agents_allowed and is_free_agent:
        return HttpResponse("❌ That event does not allow free agents.")
    if not event.active_players_allowed and is_active_player:
        return HttpResponse("❌ That event does not allow active players.")  
    if event.use_spent_limit and player.spent > event.spent_limit:
        return HttpResponse(f"❌ That event does not allow players who have spent more than ${event.spent_limit}.")      
    # Add the entree
    entree = Entree(
        player=player,
        event=event,
    )
    entree.save()
    # Return the success message (refresh page and clear form)
    return HttpResponse("✅ Player added to event successfully!")

def remove_entree(request):
    return HttpResponse("Leaving event")

events/templates/events/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="color-scheme" content="dark">
        <!-- Stylesheets -->
        <link rel="stylesheet" href="{% static 'main/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/Navbar-Right-Links-Dark-icons.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/home-styles.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/dark-mode.css' %}">
        <!-- Scripts -->
        <script src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- Dark mode css variant -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" rel="stylesheet">
        <script src="https://unpkg.com/htmx.org@1.8.6" defer></script>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4085265783135188" crossorigin="anonymous"></script>
        <!-- Favicon -->
        <link rel="icon" href="https://i.imgur.com/6YtIrWs.png">
        <!-- Content block -->
        {% block title %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-dark navbar-expand-md bg-dark py-3">
            <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}"><img class="rounded-circle" src="https://i.imgur.com/R9zJu3s.png" style="height:30px; width:30px; margin-right: 5px;"></i></span><span style="color: white !important;">EVENTS </span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a style="color: white !important;" class="nav-link" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a style="color: white !important;" class="nav-link" href="{% url 'events:index' %}">Events</a></li>
                </ul>
            </div>
        </nav>
        <!-- Messages -->
        {% if messages %}
            <div class="alert alert-primary text-white" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <!-- Block content -->
        {% block content %}{% endblock %}
    </body>
</html>

events/templates/events/index.html
{% extends "events/base.html" %}
{% load static %}
{% load main_filters %}
{% block content %}
    <!-- List all events -->
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-5">
                    <!-- Create card for each event -->
                    {% for event in events %}
                        <div class="card">
                            <div class="card-header">
                                <h3>{{ event.title }}</h3>
                            </div>
                            <div class="card-body">
                                <!-- Create a badge for each -->
                                {% if event.rookies_allowed %}
                                    <span class="badge bg-primary badge-primary">Rookies Allowed</span>
                                {% endif %}
                                {% if event.free_agents_allowed %}
                                    <span class="badge bg-primary badge-primary">Free Agents Allowed</span>
                                {% endif %}
                                {% if event.active_players_allowed %}
                                    <span class="badge bg-primary badge-primary">Active Players Allowed</span>
                                {% endif %}
                                {% if event.use_spent_limit %}
                                    <span class="badge bg-primary badge-primary"><= ${{ event.spent_limit }}</span>
                                {% endif %}
                                <hr>
                                <p>{{ event.description }}</p>
                                <p id="join-event-status"></p>
                                <hr>
                                <a href="{% url 'events:view_event' event.id %}" class="btn btn-dark btn-sm text-white">Join event</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}