hoops/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(route='', view=include('main.urls')),
    path(route='stats/', view=include('stats.urls')),
    path(route='polls/', view=include('polls.urls')),
    path(route='events/', view=include('events.urls')),
    path(route='wrestling/', view=include('wrestling.urls')),
    path(route='admin/', view=admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # Discord URL patterns
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("login/discord/", views.login_discord, name="login_discord"),
    path("login/discord/redirect/", views.login_discord_redirect, name="login_discord_redirect"),
    path("logout/", views.logout, name="logout"),

    # Player URL patterns
    path("player/<int:id>/", views.player, name="player"),
    path("player/upgrade/<int:id>/", views.upgrade_player, name="upgrade_player"),
    path("player/create/", views.create_player, name="create_player"),
    path("players/", views.free_agents, name="players"),
    path("logs/upgrades/<int:id>/", views.upgrade_logs, name="upgrade_logs"),
    path("logs/cash/<int:id>/", views.cash_logs, name="cash_logs"),
    path("players/builder/", views.mock_builder, name="mock_builder"),
    path("players/vitals/update/<int:id>/", views.update_player_vitals, name="update_player_vitals"),
    path("players/pending/update/", views.update_player_pending_upgrades, name="update_player_pending_upgrades"),
    path("player/physicals/edit/<int:id>/", views.edit_physicals, name="edit_physicals"),
    # path("players/free-agents/", views.free_agents, name="free_agents"),
    path("player/styles/<int:id>/", views.player_styles, name="player_styles"),
    path("player/cash/add/", views.add_player_cash, name="add_player_cash"),
    path("player/cash/take/", views.take_player_cash, name="take_player_cash"),
    path("player/daily/reward/collect/", views.daily_rewards, name="daily_rewards"),
    path("player/upgrade/scrape/<int:id>/", views.scrape_tendencies, name="scrape_tendencies"),
    path("player/integrate/", views.integrate_player, name="integrate_player"),

    # Team URL patterns
    path("team/<int:id>/", views.team, name="team"),
    path("teams/", views.teams, name="teams"),
    path("team/trade/", views.trade, name="trade"),
    path("team/trade/accept/<int:id>/", views.accept_trade, name="accept_trade"),
    path("team/trade/decline/<int:id>/", views.decline_trade, name="decline_trade"),
    path("trades/panel/", views.trade_panel, name="trade_panel"),
    path("team/trade/finalize/", views.check_finalize_trade, name="check_finalize_trade"),

    # Miscellaneous URL patterns
    path("upgrades/pending/", views.upgrades_pending, name="upgrades_pending"),
    path("frivolities/", views.frivolities, name="frivolities"),
    path("coupons/", views.coupons, name="coupons"),
    path("ads.txt", views.ad_view.as_view()),

    # Htmx URL patterns
    path("players/search/", views.check_player_search, name="check_player_search"),
    path("teams/search/", views.check_team_search, name="check_team_search"),
    path("coupons/redeem/", views.check_coupon_code, name="check_coupon_code"),
    path("keys/redeem/", views.check_license_key, name="check_license_key"),
    path("players/attributes/", views.check_starting_attributes, name="check_starting_attributes"),
    path("positions/count/", views.check_position_count, name="check_position_count"),
    path("upgrades/validate/", views.check_upgrade_validation, name="check_upgrade_validation"),
    path("players/leaders/", views.check_player_leaders, name="check_player_leaders"),
    path("metas/leaders/", views.check_meta_leaders, name="check_meta_leaders"),
    path("attributes/leaders/", views.check_attribute_leaders, name="check_attribute_leaders"),
    path("teams/roster/", views.check_team_roster, name="check_team_roster"),
    path("teams/trade/", views.check_trade_validation, name="check_trade_validation"),
    path("notifications/mark/read/", views.check_read_notification, name="check_read_notification"),
    path("player/daily/reward/", views.check_daily_reward, name="check_daily_reward"),
    path("player/weight/check/", views.check_weight_change, name="check_weight_change"),
    path("players/free-agents/search/", views.check_free_agent_search, name="check_free_agent_search"),
    path("contract/offer/", views.check_contract_offer, name="check_contract_offer"),
    path("contract/revoke/", views.check_contract_revoke, name="check_contract_revoke"),
    path("players/create/spent/", views.check_creation_spent, name="check_creation_spent"),
    path("players/integrate/", views.check_player_integration, name="check_player_integration"),

    # User URL patterns
    path("user/notifications/<int:id>/", views.notifications, name="notifications"),

    # API URL patterns
    path('players/cyberfaces/api/', views.cyberface_check, name='cyberface_check'),
    path('players/auto-collect/', views.auto_collect, name='auto_collect'),

]

stats/urls.py
from django.urls import path
from . import views

app_name = 'stats'
urlpatterns = [

    # Main URL patterns
    path('', views.index, name='index'),
    path('games/add/', views.add_game, name='add_game'),
    path('games/view/<int:id>/', views.view_game, name='view_game'),
    path('seasons/view/<int:id>/', views.view_season, name='view_season'),
    path('seasons/averages/view/<int:id>/', views.view_season_stats, name='view_season_stats'),

    # HTMX URL patterns
    path('roster/', views.check_stats_roster, name='check_stats_roster'),
    path('games/add/validate/', views.validate_game, name='validate_game'),
    path('seasons/averages/sort/<int:page>/', views.sort_stats, name='sort_stats'),
    path('seasons/averages/options/', views.find_options, name='find_options'),

    # API URL patterns
    path('seasons/averages/api/', views.season_stats_api, name='season_stats_api'),
    

]

main/models.py
# Django imports
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Custom imports
from .managers import DiscordAuthorizationManager
from .league import config as league_config


# DiscordUser Models
class DiscordUser(models.Model):
    # Custom Manager
    objects = DiscordAuthorizationManager()
    # Discord User Model
    id = models.BigIntegerField(primary_key=True, serialize=False)
    discord_tag = models.CharField(max_length=100)
    avatar = models.CharField(max_length=100)
    public_flags = models.IntegerField()
    flags = models.IntegerField()
    locale = models.CharField(max_length=100)
    mfa_enabled = models.BooleanField()
    last_login = models.DateTimeField(null=True)
    last_reward = models.DateTimeField(null=True)
    # Permissions
    can_update_players = models.BooleanField(default=False)
    can_approve_trades = models.BooleanField(default=False)
    can_update_styles = models.BooleanField(default=False)
    can_edit_events = models.BooleanField(default=False)
    can_edit_scores = models.BooleanField(default=False)
    # Player Slots
    player_slots = models.SmallIntegerField(default=league_config.max_players)
    auto_collect_rewards = models.BooleanField(default=False)
    can_change_styles = models.BooleanField(default=False)

    # Discord User Methods
    def is_authenticated(self, request):
        return True

    def __str__(self):
        return f"{self.discord_tag}"


# Player Models
class Player(models.Model):
    # Player Model
    first_name = models.CharField(default="Unknown", max_length=16)
    last_name = models.CharField(default="Player", max_length=16)
    cyberface = models.SmallIntegerField(default=0)
    height = models.SmallIntegerField(
        choices=league_config.height_choices, default=league_config.height_choices[0][0]
    )
    weight = models.IntegerField(
        validators=[
            MinValueValidator(league_config.player_weight_min),
            MaxValueValidator(league_config.player_weight_max),
        ]
    )
    primary_position = models.CharField(
        max_length=2,
        choices=league_config.position_choices,
        default=league_config.position_choices[0][0],
    )
    secondary_position = models.CharField(
        max_length=2,
        choices=league_config.position_choices,
        default=league_config.position_choices[0][0],
    )
    jersey_number = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(99)]
    )
    headshot = models.CharField(
        max_length=100,
        default=league_config.initial_headshot,
        blank=True,
    )
    # Attributes & Badges
    primary_attributes = models.JSONField(null=True, blank=True)
    secondary_attributes = models.JSONField(null=True, blank=True)
    primary_badges = models.JSONField(null=True, blank=True)
    secondary_badges = models.JSONField(null=True, blank=True)
    # Player Currencies
    primary_currency = models.BigIntegerField(
        name="cash", default=league_config.primary_currency_start
    )
    salary = models.PositiveBigIntegerField(name="salary", default=0)
    cap_hit = models.PositiveBigIntegerField(name="cap_hit", default=0)
    spent = models.PositiveBigIntegerField(name="spent", default=0)
    # Player Contract Details
    contract_ends_after = models.SmallIntegerField(default=999)
    contract_option = models.CharField(
        max_length=54,
        choices=league_config.contract_option_choices,
        default=league_config.contract_option_choices[0][0],
    )
    contract_benefits = models.CharField(
        max_length=54,
        choices=league_config.contract_benefit_choices,
        default=league_config.contract_benefit_choices[0][0],
    )
    contract_notes = models.CharField(max_length=100, blank=True, null=True)
    # Relationships
    discord_user = models.ForeignKey(
        "DiscordUser", blank=True, null=True, on_delete=models.CASCADE
    )
    current_team = models.ForeignKey(
        "Team", blank=True, null=True, on_delete=models.CASCADE
    )
    history_list = models.ForeignKey("HistoryList", on_delete=models.CASCADE)
    years_played = models.SmallIntegerField(default=1)
    upgrades_pending = models.BooleanField(default=False)
    free_agent = models.BooleanField(default=True)
    use_game_tendencies = models.BooleanField(default=True)
    is_rookie = models.BooleanField(default=False)
    # Attributes, Badges, & Hotzones
    styles = models.JSONField(default=league_config.get_default_styles, blank=True)
    statics = models.JSONField(default=league_config.get_default_statics)
    attributes = models.JSONField(default=league_config.get_default_attributes)
    badges = models.JSONField(default=league_config.get_default_badges)
    hotzones = models.JSONField(default=league_config.get_default_hotzones)
    tendencies = models.JSONField(default=league_config.get_default_tendencies)
    # Spent rewards
    badge_upgrades_given = models.PositiveSmallIntegerField(default=0)
    # Player Methods
    def __str__(self):
        return f"[{self.id}] {self.first_name} {self.last_name}"


# List Models (for players)
class HistoryList(models.Model):
    history = models.JSONField(default=league_config.get_default_history, blank=True)


# Team & Statistic Models
class Team(models.Model):
    # Team Model
    name = models.CharField(max_length=32)
    logo = models.CharField(max_length=100, default=league_config.initial_team_logo)
    abbrev = models.CharField(max_length=3)
    picks = models.JSONField(
        default=league_config.get_default_picks, blank=True, null=True
    )
    plays_in_main_league = models.BooleanField(default=True)
    show_on_lists = models.BooleanField(default=True)
    # Relationships
    manager = models.ForeignKey(
        "DiscordUser", blank=True, null=True, on_delete=models.CASCADE
    )
    history_list = models.ForeignKey("HistoryList", on_delete=models.CASCADE)

    # Team Methods
    def __str__(self):
        return f"{self.name}"


# Currency Transaction Models
class Transaction(models.Model):
    # Transaction Model
    transaction_type = models.CharField(
        max_length=16,
        choices=league_config.transaction_type_choices,
        default=league_config.transaction_type_choices[0][0],
    )
    amount = models.PositiveBigIntegerField()
    reason = models.CharField(max_length=100, blank=True)
    # Relationships
    giver = models.ForeignKey("DiscordUser", on_delete=models.CASCADE)
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=False)

    # Transaction Methods
    def __str__(self):
        return f"{self.transaction_type}: {self.amount}"


# Trade Models
class TradeOffer(models.Model):
    # Trade Offer Model
    offer = models.JSONField(default=league_config.get_default_trade_offer)
    accepted = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    finalized = models.BooleanField(default=False)
    notes = models.CharField(max_length=100, blank=True)
    # Relationships
    sender = models.ForeignKey("Team", on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(
        "Team", on_delete=models.CASCADE, related_name="receiver"
    )

    # Trade Offer Methods
    def __str__(self):
        return f"{self.sender} -> {self.receiver}"


# Offer Models
class ContractOffer(models.Model):
    # Contract Offer Model
    years = models.PositiveSmallIntegerField()
    salary = models.PositiveBigIntegerField()
    option = models.CharField(
        max_length=54,
        choices=league_config.contract_option_choices,
        default=league_config.contract_option_choices[0][0],
    )
    benefits = models.CharField(
        max_length=54,
        choices=league_config.contract_benefit_choices,
        default=league_config.contract_benefit_choices[0][0],
    )
    notes = models.CharField(max_length=100, blank=True, null=True, default="No notes.")
    # Relationships
    team = models.ForeignKey("Team", on_delete=models.CASCADE)
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    # Boolean Fields
    accepted = models.BooleanField(default=False)

    # Contract Offer Methods
    def __str__(self):
        return f"{self.team.abbrev} -> {self.player.first_name} {self.player.last_name}"


# Coupon Models
class Coupon(models.Model):
    code = models.CharField(max_length=16, unique=True)
    name = models.CharField(max_length=16, default="Default Coupon")
    amount = models.PositiveBigIntegerField()
    one_use = models.BooleanField(default=False)
    used = models.BooleanField(default=False)

    # Coupon Methods
    def __str__(self):
        return f"{self.code}"


# Notification Models
class Notification(models.Model):
    # Notifcation Model
    title = models.CharField(max_length=32, default="Notification")
    message = models.CharField(max_length=100, default="Content")
    read = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=False)
    # Relationships
    discord_user = models.ForeignKey("DiscordUser", on_delete=models.CASCADE)


# Award Models
class Award(models.Model):
    # Award Model
    name = models.CharField(
        max_length=6,
        choices=league_config.award_name_choices,
        default=league_config.award_name_choices[0][0],
    )
    description = models.CharField(max_length=16, default="Description")
    # Relationships
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    season = models.PositiveSmallIntegerField(default=1)

    # Award Methods
    def __str__(self):
        return f"S{self.season} - {self.name} - {self.player}"

stats/templates/stats/ajax/sort_options_fragment.html
<select name="sort_by" class="form-control mt-1" hx-post="{% url 'stats:sort_stats' 1 %}" hx-trigger="click" hx-target="#sorted_stats_table" hx-swap="innerHTML" hx-include="[name='season']">
    <option selected>Choose a sort option</option>
    {% for sort_option in sort_options %}
        <option>{{ sort_option }}</option>
    {% endfor %}
</select>

stats/templates/stats/ajax/sort_stats_fragment.html
<table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th scope="col" style="text-transform: capitalize;">PLAYER</th>
            <th scope="col" style="text-transform: capitalize;">GP</th>
            {% for header in sort_options %} 
                <th scope="col">{{ header }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for player_data in sorted_stats %}
            <tr>
                <td>{{ player_data.1.name }}</td>
                <td>{{ player_data.1.yearly_stats.totals.gp }}</td>
                {% if index_to_use == 'averages' %}
                    <td>{{ player_data.1.yearly_stats.averages.gmsc }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.ppg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.rpg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.apg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.spg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.bpg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.tpg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.fpg }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.fgp }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.tpp }}</td>
                    <td>{{ player_data.1.yearly_stats.averages.ftp }}</td>
                {% elif index_to_use == 'totals' %}
                    <td>{{ player_data.1.yearly_stats.totals.pts }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.reb }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.ast }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.stl }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.blk }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.tov }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.fouls }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.fgm }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.fga }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.tpm }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.tpa }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.ftm }}</td>
                    <td>{{ player_data.1.yearly_stats.totals.fta }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

stats/templates/stats/ajax/team_list_fragment.html
<div id="team_container">    

    
    <!-- Home team players -->
    <div id="home_team" class="col-6 mb-1">
        <p class="fw-bold">Home Team</p>
        <select class="mb-1 form-control" name="home_team" hx-post="{% url 'stats:check_stats_roster' %}" hx-trigger="change" hx-target="#team_container" hx-swap="outerHTML"><br>
            <option value="{{ home_team.id }}" selected>{{ home_team.name }}</option>
            {% for team in teams %}
                {% if not team.id == home_team.id and not team.id == user_team.id %}
                    <option value="{{ team.id }}">{{ team.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>

    <!-- Away team players -->
    <div id="away_team" class="col-6 mb-1">
        <p class="fw-bold">Away Team</p>
        <select class="mb-1 form-control" name="away_team" hx-post="{% url 'stats:check_stats_roster' %}" hx-trigger="change" hx-target="#team_container" hx-swap="outerHTML"><br>
            <option value="{{ away_team.id }}" selected>{{ away_team.name }}</option>
            {% for team in teams %}
                {% if not team.id == away_team.id and not team.id == user_team.id %}
                    <option value="{{ team.id }}">{{ team.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>

    <!-- Game data carousel -->
    <div class="container">
        {% if home_team and away_team %}
            <!-- Score data -->
            <div class="row">
                <h2 class="mt-3 mb-3">Score Breakdown</h2>
                <div class="col-4 mb-1">
                    <input type="number" class="form-control" name="home_score" placeholder="{{ home_team.abbrev }} score">
                </div>
                <div class="col-4 mb-1">
                    <input type="number" class="form-control" name="away_score" placeholder="{{ away_team.abbrev }} score">
                </div>
                <div class="col-4 mb-1">
                    <input type="number" class="form-control" name="day" placeholder="Day #">
                </div>
                <div class="col-4 mt-1 mb-1">
                    <select class="form-control" name="game_type">
                        <option value="PRE">Preseason</option>
                        <option value="REG" selected>Regular Season</option>
                        <option value="PLY">Playoffs</option>
                        <option value="FIN">Finals</option>
                    </select>
                </div>
            </div>
            <!-- Home Team -->
            <h2 class="mt-2 mb-2">Home Team</h2>
            <hr>
            <!-- Home team data -->
            {% for player in home_team.player_set.all %}
                <hr>
                <div class="container">
                    <p>Enter data for <b>{{ player.first_name }} {{ player.last_name }}</b></p>
                    <div class="row">
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_reb" placeholder="REB">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_ast" placeholder="AST">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_stl" placeholder="STL">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_blk" placeholder="BLK">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_tov" placeholder="TOV">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fgm" placeholder="FGM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fga" placeholder="FGA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_3pm" placeholder="3PM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_3pa" placeholder="3PA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_ftm" placeholder="FTM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fta" placeholder="FTA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_oreb" placeholder="OREB">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fouls" placeholder="FOULS">
                        </div>
                    </div>
                </div>
            {% endfor %}
            <h2 class="mt-2 mb-2">Away Team</h2>
            <!-- Away team data -->
            {% for player in away_team.player_set.all %}
                <hr>
                <div class="container">
                    <p>Enter data for <b>{{ player.first_name }} {{ player.last_name }}</b></p>
                    <div class="row">
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_reb" placeholder="REB">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_ast" placeholder="AST">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_stl" placeholder="STL">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_blk" placeholder="BLK">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_tov" placeholder="TOV">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fgm" placeholder="FGM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fga" placeholder="FGA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_3pm" placeholder="3PM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_3pa" placeholder="3PA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_ftm" placeholder="FTM">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fta" placeholder="FTA">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_oreb" placeholder="OREB">
                        </div>
                        <div class="col-6 mb-1">
                            <input type="number" class="form-control" name="{{ player.id }}_fouls" placeholder="FOULS">
                        </div>
                    </div>
                </div>
            {% endfor %}
            <hr>
            <!-- Submission -->
            <div class="container mb-5">
                <h2>Submit Stats</h2>
                <p>When you're all done, submit these game stats for validation.</p>
                <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#submitModal">
                    Submit Stats
                </button>
            </div>
        {% endif %}
    </div>

</div>