hoops/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(route='', view=include('main.urls')),
    path(route='stats/', view=include('stats.urls')),
    path(route='polls/', view=include('polls.urls')),
    path(route='events/', view=include('events.urls')),
    path(route='wrestling/', view=include('wrestling.urls')),
    path(route='admin/', view=admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # Discord URL patterns
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("login/discord/", views.login_discord, name="login_discord"),
    path("login/discord/redirect/", views.login_discord_redirect, name="login_discord_redirect"),
    path("logout/", views.logout, name="logout"),

    # Player URL patterns
    path("player/<int:id>/", views.player, name="player"),
    path("player/upgrade/<int:id>/", views.upgrade_player, name="upgrade_player"),
    path("player/create/", views.create_player, name="create_player"),
    path("players/", views.free_agents, name="players"),
    path("logs/upgrades/<int:id>/", views.upgrade_logs, name="upgrade_logs"),
    path("logs/cash/<int:id>/", views.cash_logs, name="cash_logs"),
    path("players/builder/", views.mock_builder, name="mock_builder"),
    path("players/vitals/update/<int:id>/", views.update_player_vitals, name="update_player_vitals"),
    path("players/pending/update/", views.update_player_pending_upgrades, name="update_player_pending_upgrades"),
    path("player/physicals/edit/<int:id>/", views.edit_physicals, name="edit_physicals"),
    # path("players/free-agents/", views.free_agents, name="free_agents"),
    path("player/styles/<int:id>/", views.player_styles, name="player_styles"),
    path("player/cash/add/", views.add_player_cash, name="add_player_cash"),
    path("player/cash/take/", views.take_player_cash, name="take_player_cash"),
    path("player/daily/reward/collect/", views.daily_rewards, name="daily_rewards"),
    path("player/upgrade/scrape/<int:id>/", views.scrape_tendencies, name="scrape_tendencies"),
    path("player/integrate/", views.integrate_player, name="integrate_player"),

    # Team URL patterns
    path("team/<int:id>/", views.team, name="team"),
    path("teams/", views.teams, name="teams"),
    path("team/trade/", views.trade, name="trade"),
    path("team/trade/accept/<int:id>/", views.accept_trade, name="accept_trade"),
    path("team/trade/decline/<int:id>/", views.decline_trade, name="decline_trade"),
    path("trades/panel/", views.trade_panel, name="trade_panel"),
    path("team/trade/finalize/", views.check_finalize_trade, name="check_finalize_trade"),

    # Miscellaneous URL patterns
    path("upgrades/pending/", views.upgrades_pending, name="upgrades_pending"),
    path("frivolities/", views.frivolities, name="frivolities"),
    path("coupons/", views.coupons, name="coupons"),
    path("ads.txt", views.ad_view.as_view()),

    # Htmx URL patterns
    path("players/search/", views.check_player_search, name="check_player_search"),
    path("teams/search/", views.check_team_search, name="check_team_search"),
    path("coupons/redeem/", views.check_coupon_code, name="check_coupon_code"),
    path("keys/redeem/", views.check_license_key, name="check_license_key"),
    path("players/attributes/", views.check_starting_attributes, name="check_starting_attributes"),
    path("positions/count/", views.check_position_count, name="check_position_count"),
    path("upgrades/validate/", views.check_upgrade_validation, name="check_upgrade_validation"),
    path("players/leaders/", views.check_player_leaders, name="check_player_leaders"),
    path("metas/leaders/", views.check_meta_leaders, name="check_meta_leaders"),
    path("attributes/leaders/", views.check_attribute_leaders, name="check_attribute_leaders"),
    path("teams/roster/", views.check_team_roster, name="check_team_roster"),
    path("teams/trade/", views.check_trade_validation, name="check_trade_validation"),
    path("notifications/mark/read/", views.check_read_notification, name="check_read_notification"),
    path("player/daily/reward/", views.check_daily_reward, name="check_daily_reward"),
    path("player/weight/check/", views.check_weight_change, name="check_weight_change"),
    path("players/free-agents/search/", views.check_free_agent_search, name="check_free_agent_search"),
    path("contract/offer/", views.check_contract_offer, name="check_contract_offer"),
    path("contract/revoke/", views.check_contract_revoke, name="check_contract_revoke"),
    path("players/create/spent/", views.check_creation_spent, name="check_creation_spent"),
    path("players/integrate/", views.check_player_integration, name="check_player_integration"),

    # User URL patterns
    path("user/notifications/<int:id>/", views.notifications, name="notifications"),

    # API URL patterns
    path('players/cyberfaces/api/', views.cyberface_check, name='cyberface_check'),
    path('players/auto-collect/', views.auto_collect, name='auto_collect'),

]

wrestling/urls.py
from django.urls import path
from . import views

app_name = 'wrestling'
urlpatterns = [

    # Main URL patterns
    path(route='', view=views.index, name='index'),
    path(route='home/', view=views.index, name='home'),

    # Wrestler URL patterns
    path(route='wrestlers/create/', view=views.wrestler_create, name='wrestler_create'),
    path(route='wrestlers/profile/<int:wrestler_id>/', view=views.wrestler_profile, name='wrestler_profile'),
    path(route='wrestlers/upgrade/<int:wrestler_id>/', view=views.wrestler_upgrade, name='wrestler_upgrade'),

    # Roster URL Patterns
    path(route='roster', view=views.wrestling_roster, name='wrestling_roster'),

    # Titles URL Patterns
    path(route='titles', view=views.wrestling_titles, name='wrestling_titles'),
    path(route='titles/history/<int:title_id>/', view=views.wrestling_title_history, name='wrestling_title_history'),

    # Shows URL Patterns
    path(route='shows', view=views.wrestling_shows, name='wrestling_shows'),

    # HTMX URL Patterns
    path(route='htmx/wrestler/create/', view=views.htmx_wrestler_create, name='htmx_wrestler_create'),
    
    
]

main/views.py
# Django imports
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.management import call_command
from django.db.models import Q
from django.db.models import Sum
from django.template.loader import render_to_string
from django.utils import timezone
from django.views import View
from rest_framework.decorators import api_view

# Model imports
from .models import Player
from .models import Team
from .models import Coupon
from .models import Transaction
from .models import TradeOffer
from .models import ContractOffer
from .models import DiscordUser
from .models import Notification
from .models import Award

# Form imports
from .forms import PlayerForm
from .forms import UpgradeForm
from .forms import StylesForm

# Custom imports
from .discord import auth as discord_auth
from .discord import webhooks as discord_webhooks
from .league import config as league_config

# Stats imports
from stats.league.stats import compile as stats_compile
from stats.league.stats import calculate as stats_calculate

# Custom packages
import copy
import json
import random
import requests
import datetime
from requests.structures import CaseInsensitiveDict
from datetime import timedelta

from .league.player import upgrade as hoops_player_upgrade
from .league.player import create as hoops_player_create
from .league.player import physicals as hoops_player_physicals
from .league.player import export as hoops_player_export
from .league.player import style as hoops_player_style
from .league.player import scrape2KMT as hoops_player_scrape
from .league.extra import convert as hoops_extra_convert
from .league.teams import trade as hoops_team_trade
from .league.teams import offer as hoops_team_offer
from .league.user import notify as hoops_user_notify

# .ENV file import
import os, json
from dotenv import load_dotenv

load_dotenv()


# Create your views here.
def index(request):
    # Create the context
    context = {
        "title": "Home",
    }
    # Return the home page
    return render(request, "main/index.html", context)


def home(request):
    # Get the current user
    current_user = request.user
    # Find the game of the day for the past three days
    gotd_list = []
    gotd_return = stats_compile.game_of_the_day(season=league_config.current_season)
    if gotd_return:
        gotd_list.append(gotd_return)
        day_index = gotd_list[0]["day"]
        for _ in range (2):
            day_index -= 1
            if day_index > 0:
                gotd_list.append(stats_compile.game_of_the_day(season=league_config.current_season, specific=day_index))
            else:
                break
    # Create the context
    context = {
        "title": "Home",
        "current_user": current_user,
        "players": [],
        "notifications": None,
        "gotd_list": gotd_list,
        "motd": os.environ.get("MOTD"),
    }
    # Send players to home page
    if current_user.is_authenticated:
        try:
            players = Player.objects.filter(discord_user=current_user)
            # Add players to the context
            for p in players:
                context["players"].append(p)
            # Count notifications
            context["notifications"] = Notification.objects.filter(
                discord_user=current_user, read=False
            ).count()
            # Check if the user manages a team
            team = Team.objects.filter(manager=current_user).first()
            # If user manages a team, check for pending trade offers
            if team:
                # Check for pending trade offers
                pending_trades = TradeOffer.objects.filter(
                    Q(sender=team) | Q(receiver=team), accepted=False
                )
                if pending_trades:
                    messages.success(
                        request,
                        "You have pending trades! Visit the trade machine to check them out.",
                    )
        except ValueError:
            # If the user is still signed into an administration account
            redirect(logout)
    # Return the home page
    return render(request, "main/league/home.html", context)


def login(request):
    return HttpResponse("This is the login page.")


def login_discord(request):
    discord_auth_url = os.environ.get("DISCORD_AUTH_URL")
    return redirect(discord_auth_url)


def login_discord_redirect(request):
    try:
        # Get information from Discord
        code = request.GET.get("code")
        info = discord_auth.exchange_code(code)
        user = info[0]
        # Create the discord user
        discord_user = authenticate(request, user=user)
        discord_user = list(discord_user).pop()
        # Finally, log the user in
        django_login(request, discord_user, backend="main.authorize.DiscordBackend")
        # Send a success message
        messages.error(request, "You have successfully logged in!")
    except:
        # Sometimes the user will be redirected to this page without a code
        messages.error(request, "Something went wrong while logging you in, try again!")
    # Redirect the user to the home page
    return redirect(home)


def logout(request):
    django_logout(request)
    messages.error(request, "You have successfully logged out!")
    return redirect("/")


def player(request, id):
    # Check if the player exists
    plr = Player.objects.get(pk=id)
    if not plr:
        return HttpResponse("Sorry, this player doesn't exist!")
    # Get transaction history & total earnings in past week (cash_taken, cash_given, paycheck)
    transactions = Transaction.objects.filter(player=plr)
    week_earnings = 0
    # If date is in the past week, add/subtract to/from week_earnings
    for t in transactions:
        if t.date > timezone.now() - datetime.timedelta(days=7):
            if t.transaction_type == "cash_taken":
                week_earnings -= t.amount
            elif t.transaction_type == "cash_given":
                week_earnings += t.amount
    # Get the player's stats
    player_career_stats = stats_compile.player_stats(player=plr, career=True, season=None)
    player_game_logs = stats_compile.player_game_logs(player=plr, season=league_config.current_season, x=10)
    # Get possible relatives
    possible_relatives = Player.objects.filter(last_name=plr.last_name).values_list("id", "first_name")
    # Check if player has claimed daily reward
    has_collected_today = False
    if plr.discord_user and plr.discord_user.last_reward:
        if timezone.now().day == plr.discord_user.last_reward.day:
            has_collected_today = True
    # Initialize the context
    context = {
        # Page information
        "title": f"{plr.first_name} {plr.last_name}",
        "player": plr,
        "badgeEmojis": {0: "🚫", 1: "🟫", 2: "🌫️", 3: "🟨", 4: "🟪"},
        # Attribute categories
        "playmaking_attributes": league_config.attribute_categories["playmaking"],
        "shooting_attributes": league_config.attribute_categories["shooting"],
        "physical_attributes": league_config.attribute_categories["physical"],
        "defense_attributes": league_config.attribute_categories["defense"],
        "finishing_attributes": league_config.attribute_categories["finishing"],
        # Badge categories
        "finishing_badges": league_config.badge_categories["finishing"],
        "shooting_badges": league_config.badge_categories["shooting"],
        "playmaking_badges": league_config.badge_categories["playmaking"],
        "defense_badges": league_config.badge_categories["defense"],
        # Playstyles
        "playstyles": league_config.playstyles,
        "playstyle1": [
            league_config.playstyles[plr.statics["playstyles"]["playstyle1"]],
            plr.statics["playstyles"]["playstyle1"],
        ],
        "playstyle2": [
            league_config.playstyles[plr.statics["playstyles"]["playstyle2"]],
            plr.statics["playstyles"]["playstyle2"],
        ],
        "playstyle3": [
            league_config.playstyles[plr.statics["playstyles"]["playstyle3"]],
            plr.statics["playstyles"]["playstyle3"],
        ],
        "playstyle4": [
            league_config.playstyles[plr.statics["playstyles"]["playstyle4"]],
            plr.statics["playstyles"]["playstyle4"],
        ],
        # Precalled methods
        "height_in_feet": hoops_extra_convert.convert_to_height(plr.height),
        "file": json.dumps(hoops_player_export.export_player(plr), indent=4),
        # Transaction history
        "week_earnings": week_earnings,
        # Player stats
        "player_career_stats": player_career_stats,
        "player_game_logs": player_game_logs,
        # Possible relatives
        "possible_relatives": possible_relatives,
        # Daily rewards
        "has_collected_today": has_collected_today,
        # Total badge points
        "total_badge_points": hoops_player_upgrade.total_badge_points(plr)
    }
    return render(request, "main/players/player.html", context)


@login_required(login_url="/login/discord/")
def upgrade_player(request, id):
    # Collect user & player information
    user = request.user
    # Check if the player exists
    player = Player.objects.get(pk=id)
    if not player:
        return HttpResponse("Sorry, this player doesn't exist!")
    # Check if player has been integrated
    if not player.primary_attributes or not player.secondary_attributes or not player.primary_badges or not player.secondary_badges:
        return redirect(integrate_player)
    # Check if the user has permission to upgrade this player
    if not player.discord_user == user:

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="color-scheme" content="dark">
        <!-- Stylesheets -->
        <link rel="stylesheet" href="{% static 'main/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/Navbar-Right-Links-Dark-icons.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/home-styles.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/dark-mode.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/players/extra.css' %}">
        <!-- Scripts -->
        <script src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
        <!-- Dark mode css variant -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" rel="stylesheet">
        <script src="https://unpkg.com/htmx.org@1.8.6" defer></script>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4085265783135188" crossorigin="anonymous"></script>
        <!-- Favicon -->
        <link rel="icon" href="https://i.imgur.com/6YtIrWs.png">
        <!-- Content block -->
        {% block title %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-dark navbar-expand-md bg-dark py-3">
            <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}"><img class="rounded-circle" src="https://i.imgur.com/R9zJu3s.png" style="height:30px; width:30px; margin-right: 5px;"></i></span><span style="color: white !important;">HOOPSIM </span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-5">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a style="color: white !important;" class="nav-link" href="/">Home</a></li>
                        <li class="nav-item"><a style="color: white !important;" class="nav-link" href="/players">Players</a></li>
                        <li class="nav-item"><a style="color: white !important;" class="nav-link" href="/teams">Teams</a></li>
                    </ul>
                    {% if current_user.is_authenticated != False %}
                        <a style="color: white !important;" class="btn btn-primary btn-sm ms-md-2" role="button" href="/logout">Logout</a>
                    {% else %}
                        <a style="color: white !important;" class="btn btn-primary btn-sm ms-md-2" role="button" href="/login/discord">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- Messages -->
        {% if messages %}
            <div class="alert alert-primary text-white" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <!-- Block content -->
        {% block content %}{% endblock %}
    </body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" style>
    <head>
        <title>Hoopsim</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="color-scheme" content="dark">
        <!-- Stylesheets -->
        <link rel="stylesheet" href="{% static 'main/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/Navbar-Right-Links-Dark-icons.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/home-styles.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/dark-mode.css' %}">
        <!-- Scripts -->
        <script src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- Dark mode css variant -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" rel="stylesheet">
        <script src="https://unpkg.com/htmx.org@1.8.6" defer></script>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4085265783135188" crossorigin="anonymous"></script>
        <!-- Favicon -->
        <link rel="icon" href="https://i.imgur.com/6YtIrWs.png">
    </head>

    <body>
        <div class="container py-4 py-xl-5">
            <div class="row gy-4 gy-md-0">
                <div class="col-md-6">
                    <div class="p-xl-5 m-xl-5"><img class="rounded img-fluid w-100 fit-cover" style="min-height: 300px;" src="https://i.imgur.com/HZVQUf1.png" /></div>
                </div>
                <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                    <div style="max-width: 350px;">
                        <h2 class="text-uppercase fw-bold">HOOPSIM</h2>
                        <p class="my-3">Tools built for the community.</p>
                        <a class="btn btn-primary text-white" role="button" href="{% url 'home' %}">Basketball</a>
                        <a class="btn btn-primary text-white" role="button" href="{% url 'wrestling:index' %}">Wrestling</a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>